services:
  ollama:
    restart: unless-stopped
    ports:
      - "11434:11434"
    build: .
    volumes:
      - ./data:/root/.ollama
    container_name: ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - OLLAMA_KEEP_ALIVE=-1
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]